### ISSUE TITLE
Add link to demo front page

### ISSUE THREAD

**Issue by kathrynwp** [mendezcode/wpcom-demo-viewer#3]
It would be very handy to have a link to the demo's homepage that opens in a new window. (`target="_blank"`)

I often need to view the site in a larger window, and having a link to the demo in a consistent spot would be extremely helpful. 

Right now I right-click the "View site" link in the superadmin bar, or right-click on the site title, but it would be more ergonomic and efficient to have a link in the same place -- maybe next to the current "Customizer" link? -- that opens in a new window by default.

Suggested location for new link:

![dropbox-2](https://cloud.githubusercontent.com/assets/7662449/16671296/aa785d8c-446c-11e6-8f45-652cb9f5a5f0.png)

**Comment by mendezcode** [comment]
Took care of it on abe923a60ba8e429fd627c8c7805404f60fadfb5 ;-)
